
UPDATE CUSTOMER SET 
       CUSTOMER.GBG_ID = (SELECT TCV_CUSTOMER_TEMP.GBG_ID FROM 
                             TCV_CUSTOMER_TEMP WHERE 
                             CUSTOMER.CUST_REF_NUM = TCV_CUSTOMER_TEMP.CUST_REF_NUM AND 
                             CUSTOMER.BRANCH_BUDGET_CTR = TCV_CUSTOMER_TEMP.BRANCH) 
      where EXISTS (SELECT TCV_CUSTOMER_TEMP.GBG_ID FROM 
                      TCV_CUSTOMER_TEMP  WHERE 
                      CUSTOMER.CUST_REF_NUM = TCV_CUSTOMER_TEMP.CUST_REF_NUM AND 
                      CUSTOMER.BRANCH_BUDGET_CTR = TCV_CUSTOMER_TEMP.BRANCH AND 
                      CUSTOMER.GBG_ID is null)
