BEGIN
  FOR o IN
  (SELECT GBG_ID,CUST_REF_NUM,BRANCH FROM TCV_CUSTOMER_TEMP
  )
  LOOP
    UPDATE CUSTOMER
    SET CUSTOMER.GBG_ID            =o.GBG_ID
    WHERE CUSTOMER.CUST_REF_NUM    = o.CUST_REF_NUM
    AND CUSTOMER.BRANCH_BUDGET_CTR = o.BRANCH;
  END LOOP;
END;
